#!/bin/bash
# Load resources
 
#xrdb -merge .Xresources
 
# Set up an icon tray
 
trayer --edge top --align center --SetDockType true --SetPartialStrut true \
 --expand true --width 10  --transparent true --tint 0x000011 --height 15 &
 
# Set the background color
 
#xsetroot -bitmap 
feh --bg-scale /home/alionka/Pictures/background.png&
# Fire up apps
 
#gajim &
 
#xscreensaver -no-splash &
 
if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi
 
if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 3
   gnome-power-manager
fi

if [ -x /usr/bin/gnome-screensaver] ; then
    sleep 3
    gnome-screensaver
fi

if [ -x /usr/bin/gnome-screensaver] ; then
    sleep3
    gnome-screensaver
fi
 
exec .xmonad/xmonad-i386-linux
